### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by sucof** [feix760/Chrome_12306#10]
npm v5.6
nodejs v8.9.4
```
RROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/page/index/component/login/index.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/home/ro4k/Chrome_12306/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/home/ro4k/Chrome_12306/node_modules/node-sass/lib/extensions.js:128:13)
    at foundBinariesList (/home/ro4k/Chrome_12306/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/ro4k/Chrome_12306/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/ro4k/Chrome_12306/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/ro4k/Chrome_12306/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/ro4k/Chrome_12306/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ro4k/Chrome_12306/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at loadLoader (/home/ro4k/Chrome_12306/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/home/ro4k/Chrome_12306/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/home/ro4k/Chrome_12306/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /home/ro4k/Chrome_12306/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/home/ro4k/Chrome_12306/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/home/ro4k/Chrome_12306/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/home/ro4k/Chrome_12306/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/home/ro4k/Chrome_12306/node_modules/webpack/lib/NormalModule.js:182:3)
 @ ./src/page/index/component/login/index.scss 4:14-141
 @ ./src/page/index/component/login/index.js
 @ ./src/page/index/index.js
```

**Comment by bumblebeehub** [comment]
一样的错误

ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/page/index/component/login/index.scss
Module build failed: Error: ENOENT: no such file or directory, scandir 'F:\Chrome_12306-master\node_modules\node-sass\vendor'
    at Object.fs.readdirSync (fs.js:912:18)
    at Object.getInstalledBinaries (F:\Chrome_12306-master\node_modules\node-sass\lib\extensions.js:128:13)
    at foundBinariesList (F:\Chrome_12306-master\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (F:\Chrome_12306-master\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (F:\Chrome_12306-master\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (F:\Chrome_12306-master\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (F:\Chrome_12306-master\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\Chrome_12306-master\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at loadLoader (F:\Chrome_12306-master\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (F:\Chrome_12306-master\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (F:\Chrome_12306-master\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at F:\Chrome_12306-master\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (F:\Chrome_12306-master\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (F:\Chrome_12306-master\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (F:\Chrome_12306-master\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (F:\Chrome_12306-master\node_modules\webpack\lib\NormalModule.js:182:3)
 @ ./src/page/index/component/login/index.scss 4:14-141
 @ ./src/page/index/component/login/index.js
 @ ./src/page/index/index.js

ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/page/index/index.scss
Module build failed: Error: ENOENT: no such file or directory, scandir 'F:\Chrome_12306-master\node_modules\node-sass\vendor'
    at Object.fs.readdirSync (fs.js:912:18)
    at Object.getInstalledBinaries (F:\Chrome_12306-master\node_modules\node-sass\lib\extensions.js:128:13)
    at foundBinariesList (F:\Chrome_12306-master\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (F:\Chrome_12306-master\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (F:\Chrome_12306-master\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (F:\Chrome_12306-master\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (F:\Chrome_12306-master\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\Chrome_12306-master\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at loadLoader (F:\Chrome_12306-master\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (F:\Chrome_12306-master\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (F:\Chrome_12306-master\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at F:\Chrome_12306-master\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (F:\Chrome_12306-master\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (F:\Chrome_12306-master\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (F:\Chrome_12306-master\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (F:\Chrome_12306-master\node_modules\webpack\lib\NormalModule.js:182:3)
 @ ./src/page/index/index.scss 4:14-129
 @ ./src/page/index/index.js

**Comment by bumblebeehub** [comment]
已解决，先把node-sass remove再重新安装即可

**Comment by feix760** [comment]
这是开始的时候node-sass安装失败 
出现这种错误可以用 @bumblebeehub  的方法 `npm i node-sass` 试试

**Comment by sucof** [comment]
谢谢 @bumblebeehub
