### ISSUE TITLE
验证码提交失败

### ISSUE THREAD

**Issue by sucof** [feix760/Chrome_12306#12]
使用自动验证码提交会出现如下错误：获取自动识别验证码失败 undefined.
代码错误提示：
```
Error: non-error thrown: [object Object]
      at Object.onerror (~/Chrome_12306/node_modules/koa/lib/context.js:108:40)
      at onerror (~/Chrome_12306/node_modules/koa/lib/application.js:147:32)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by kongyong16** [comment]
同样问题

000009无需输入验证码，自动提交订单...
000010余票: 2张 无座: 192张 排队人数: 0
000011提交失败 SyntaxError: Unexpected token < in JSON at position 0

**Comment by feix760** [comment]
> 000011提交失败 SyntaxError: Unexpected token < in JSON at position 0

@kongyong16 这个问题是12306拥挤导致的，在网速好的情况下可以减少此问题出现的概念
